version: '2'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
    ports:
      - "80:80"
  auth:
      image: nginx:alpine
      volumes:
        - .:/var/www/html
        - ./docker/nginx/auth.conf:/etc/nginx/conf.d/default.conf
      links:
        - fpm
      ports:
        - "8080:80"
  fpm:
    build: ./docker/fpm
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.168
